### ISSUE TITLE
NullPointerException on startup

### ISSUE THREAD

**Issue by chrisgoffinet** [instaclustr/cassandra-exporter#11]
Tried the latest release, noticed this NPE on startup, I think it might be related to the fact im using G1 for Cassandra and not CMS:

```WARN  [prometheus-netty-pool-0] 2018-10-13 18:39:54,114 Harvester.java:214 - Metrics collector java.lang:type=GarbageCollector failed to collect. Skipping.
WARN  [prometheus-netty-pool-0] 2018-10-13 18:37:14,350 Harvester.java:214 - Metrics collector java.lang:type=GarbageCollector failed to collect. Skipping.
java.lang.NullPointerException: null
	at com.zegelin.prometheus.cassandra.collector.jvm.GarbageCollectorMXBeanMetricFamilyCollector.collect(GarbageCollectorMXBeanMetricFamilyCollector.java:77) ~[cassandra-exporter-agent-0.9.3.jar:na]
	at com.zegelin.prometheus.cassandra.Harvester.lambda$collect$3(Harvester.java:211) ~[cassandra-exporter-agent-0.9.3.jar:na]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[na:1.8.0_181]
	at java.util.HashMap$EntrySpliterator.tryAdvance(HashMap.java:1717) ~[na:1.8.0_181]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) ~[na:1.8.0_181]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[na:1.8.0_181]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169) ~[na:1.8.0_181]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[na:1.8.0_181]
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_181]
	at com.zegelin.prometheus.exposition.TextFormatChunkedInput.nextSlice(TextFormatChunkedInput.java:309) ~[cassandra-exporter-agent-0.9.3.jar:na]
	at com.zegelin.prometheus.exposition.TextFormatChunkedInput.readChunk(TextFormatChunkedInput.java:357) ~[cassandra-exporter-agent-0.9.3.jar:na]
	at com.zegelin.prometheus.exposition.TextFormatChunkedInput.readChunk(TextFormatChunkedInput.java:26) ~[cassandra-exporter-agent-0.9.3.jar:na]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:225) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:139) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:797) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:808) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:789) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:825) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at com.zegelin.prometheus.netty.HttpHandler.sendMetrics(HttpHandler.java:275) ~[cassandra-exporter-agent-0.9.3.jar:na]
	at com.zegelin.prometheus.netty.HttpHandler.channelRead0(HttpHandler.java:88) ~[cassandra-exporter-agent-0.9.3.jar:na]```

**Comment by zegelin** [comment]
Thanks for the bug report and PR. Merged.

I'll be doing the v0.9.4 release shortly, which will contain your changes.
