### ISSUE TITLE
exporter incompatible with cassandra trunk (4.0)

### ISSUE THREAD

**Issue by rustyrazorblade** [instaclustr/cassandra-exporter#23]
When trying to collect metrics from trunk I've run into this:

```
WARN  [prometheus-netty-pool-0] 2019-05-01 15:22:18,501 Slf4JLogger.java:151 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoSuchMethodError: org.apache.cassandra.utils.FBUtilities.getBroadcastAddress()Ljava/net/InetAddress;
	at com.zegelin.prometheus.cassandra.InternalMetadataFactory.localBroadcastAddress(InternalMetadataFactory.java:85)
	at com.zegelin.prometheus.cassandra.Harvester.globalLabels(Harvester.java:280)
	at com.zegelin.prometheus.netty.HttpHandler.sendMetrics(HttpHandler.java:283)
	at com.zegelin.prometheus.netty.HttpHandler.channelRead0(HttpHandler.java:91)
	at com.zegelin.prometheus.netty.HttpHandler.channelRead0(HttpHandler.java:36)
```

The call `FBUtilities.getBroadcastAddress()` was removed in process of making C* run multiple instances on one machine.  It should be replaced with ``FBUtilities.getLocalAddressAndPort``

**Comment by zegelin** [comment]
Yes, support for multiple newer & older versions of Cassandra is pretty much non-existent at this point.

We've been working on building a test framework that lets us verify that changes to the exporter codebase don't effect the output. Once that's complete we hope to refactor the code to support multiple versions.

**Comment by rustyrazorblade** [comment]
OK.  Happy to help test it out once you've got something to hammer on.

**Comment by Rashmi-lab** [comment]
Are there any plans to merge this exporter changes in to the main branch, so that it would be compatible with cassandra version 4.0?
