### ISSUE TITLE
Broken pipe IOException

### ISSUE THREAD

**Issue by mkey-cdx** [instaclustr/cassandra-exporter#38]
This exception is thrown regularly. I cannot link it to a specific event or cluster state but it sometime overlaps with scrapping timeouts ( which we set to 20s FYI).
I could see it thrown even on idle mono-node cassandra cluster.

```
WARN  [prometheus-netty-pool-0] 2019-11-10 06:02:40,697 Slf4JLogger.java:151 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[na:1.8.0_181]
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[na:1.8.0_181]
        at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[na:1.8.0_181]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[na:1.8.0_181]
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:336) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:802) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:313) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:770) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1256) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:763) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:744) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:530) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:355) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:763) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:744) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:763) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:744) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:311) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:139) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:797) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:808) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:789) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:825) [netty-all-4.0.44.Final.jar:4.0.44.Final]
        at com.zegelin.cassandra.exporter.netty.HttpHandler.sendMetrics(HttpHandler.java:299) [cassandra-exporter-agent-0.9.8.jar:na]
        at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:91) [cassandra-exporter-agent-0.9.8.jar:na]
        at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:36) [cassandra-exporter-agent-0.9.8.jar:na] 
```

It this harmful? Can this be related to timeouts we observed from time to time?
Note that we use the exporter as java agent.

**Comment by eperott** [comment]
I've observed this in a 2-node ccm cluster while trying to reproduce other errors.

I can reproduce this by quickly reloading the metrics page in my browser.

**Comment by zegelin** [comment]
My guess is this is Netty throwing an exception that the socket has been closed from the other side.

I guess we could suppress it...

**Comment by eperott** [comment]
Yes, I believe you are right.

I'm thinking we could solve this in a dedicated handler that we put last in the Netty pipeline. Rather than printing the full stack trace at WARN level, we could print the error message only at DEBUG level. 

We should probably check for the "Broken pipe" message specifically as we still probably want the full stack trace on other kinds of IOException.

WDYT?

**Comment by zegelin** [comment]
That sounds like a reasonable solution.

Shame that we'd have to resort to string matching here, but better than nothing.

**Comment by eperott** [comment]
> ...but better than nothing.

Yeah, I think so.

I'd be happy to create a small patch based on the proposal above.
