### ISSUE TITLE
Failed to register collector for some of ClientRequest MBean types in Cassandra 3.0.15

### ISSUE THREAD

**Issue by podile** [instaclustr/cassandra-exporter#45]
Hi,
I have observed below warning messages where agent is failed to register collector for some of ClientRequest MBean types in in Cassandra 3.0.15. Has anyone faced the same issue? If so, please provide the work-around you have. 

```
2019-12-09 09:43:29,346 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,347 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=TotalLatency.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,348 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Timeouts.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,349 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Unavailables.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,349 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Failures.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,352 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Latency.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,353 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=TotalLatency.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,353 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Timeouts.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,354 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Unavailables.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:29,355 [WARN ] [cassandra-exporter-harvester-defer-0]  Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra.metrics:type=ClientRequest,scope=Write,name=Failures.
java.lang.NullPointerException: null
        at java.util.HashMap.putMapEntries(HashMap.java:501) ~[na:1.8.0_162]
        at java.util.HashMap.putAll(HashMap.java:785) ~[na:1.8.0_162]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:65) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:91) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174) ~[cassandra-exporter-agent-0.9.9.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
2019-12-09 09:43:36,548 [INFO ] [main]  CassandraDaemon.java:687 - No gossip backlog; proceeding



```

Thanks,
Rohini Podile.

**Comment by eperott** [comment]
Looks like a duplicate of #43

**Comment by podile** [comment]
Yes... Thanks @eperott . Closing the ticket now
