### ISSUE TITLE
Broken pipe IOException every 5 minutes

### ISSUE THREAD

**Issue by christidis** [instaclustr/cassandra-exporter#94]
In a 3-node Cassandra cluster, the graphs from one node are not consistent in Grafana, they have gaps and Prometheus reports timeouts. I have tried increasing timeout to 30s but this didn't help.

In the logs I can see this warning which is due to the timeouts according to https://github.com/instaclustr/cassandra-exporter/issues/38

```
WARN  [prometheus-netty-pool-0] 2021-02-10 09:43:05,983 Slf4JLogger.java:151 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:336) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:802) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:313) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:770) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1256) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:763) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:744) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:530) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:355) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:763) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:744) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:763) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:744) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:311) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:139) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:771) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:797) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:808) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:789) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:825) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at com.zegelin.cassandra.exporter.netty.HttpHandler.sendMetrics(HttpHandler.java:299) [cassandra-exporter-agent-0.9.10.jar:na]
	at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:91) [cassandra-exporter-agent-0.9.10.jar:na]
	at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:36) [cassandra-exporter-agent-0.9.10.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-all-4.0.44.Final.jar:4.0.44.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

Debugging this I have noticed that all requests are served within 0.5-1s.

However, one request every 5 minutes (sharp) takes around 1m 40s to complete and this is causing the gaps in prometheus.
```
Wed Feb 10 17:26:22 UTC 2021
Wed Feb 10 17:31:22 UTC 2021
Wed Feb 10 17:36:21 UTC 2021
Wed Feb 10 17:41:27 UTC 2021
Wed Feb 10 17:46:27 UTC 2021
Wed Feb 10 17:51:29 UTC 2021
```

During the stuck request the CPU is between 100-120% more than the usual load.
At the same time I can see in strace an increased number of sched_yield calls
```
strace -f -c -p PID
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 37.94  573.100718      118360      4842           epoll_wait
 29.24  441.657047         297   1484940           sched_yield
 21.73  328.282601        8139     40330     19388 futex
  9.27  139.970752     2592050        54        52 restart_syscall
  1.40   21.111056       50026       422           read
  0.39    5.853749      975624         6         2 accept
  0.02    0.268233          11     22764           lstat
  0.01    0.141108         295       478           write
  0.00    0.047237          12      3642           pread64
  0.00    0.046144          14      3120           stat
  0.00    0.041572          13      3122           open
  0.00    0.036256          11      3125           close
  0.00    0.025115           8      3120           fstat
  0.00    0.020696          68       301        18 writev
  0.00    0.000827          68        12           rt_sigprocmask
  0.00    0.000535         267         2           fadvise64
  0.00    0.000489          61         8           madvise
  0.00    0.000473          78         6           mmap
  0.00    0.000351         175         2           msync
  0.00    0.000322          53         6           sched_getaffinity
  0.00    0.000223          74         3           set_robust_list
  0.00    0.000172          57         3           clone
  0.00    0.000164          27         6           mprotect
  0.00    0.000107          35         3           gettid
  0.00    0.000053           4        12         3 epoll_ctl
  0.00    0.000043          21         2           fsync
  0.00    0.000036          12         3           setpriority
  0.00    0.000017           5         3           dup2
  0.00    0.000011           1         9           fcntl
  0.00    0.000007           1         6           getsockname
  0.00    0.000004           1         3           setsockopt
  0.00    0.000004           1         3           getsockopt
  0.00    0.000000           0         1           times
  0.00    0.000000           0         1           getpriority
------ ----------- ----------- --------- --------- ----------------
100.00 1510.606122               1570360     19463 total
```

**Comment by zegelin** [comment]
1m40s for a scrape certainly sounds like something is stuck.

- Is Cassandra-exporter running as an agent or standalone?
- Are you scraping all metrics, or a subset?
- How big is the C* schema?
- What does the host's CPU load look like? Both at the time of the spike, and on the lead-up.
- How much load is the C* node receiving (request throughput, etc)?
- Any mention of GC pauses in the C* `system.log`? Any other warnings/errors?

**Comment by christidis** [comment]
- The exporter is running as an agent within Cassandra.

- I didn't exclude anything, so it requests the whole thing every time. I will give it a try with subsets and report back.
- Cassandra has ~ 112 keyspaces. 4 tables each. With `replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;`
- Each node is running on top of Docker, with 12 CPUs and 64GB RAM limit. JVM has `-Xms16g -Xmx16g` limits.
- There is no load on the host. All the other systems are responsive during the stuck request.
- During the stuck request the CPU in the container is between 100-120% more than the usual load. 1 core is being used at 100% until the request is completed. This is most probably the exporter.
- GC logs are the following
```
> docker logs -f --tail=3000 literatum-cassandra-cl01-1330 | grep GCInspector.java
INFO  [Service Thread] 2021-02-11 02:59:03,320 GCInspector.java:284 - ParNew GC in 347ms.  CMS Old Gen: 4473741472 -> 4530688632; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 159467920 -> 35288608
INFO  [Service Thread] 2021-02-11 03:00:12,356 GCInspector.java:284 - ParNew GC in 398ms.  CMS Old Gen: 4534155688 -> 4534169776; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 264440 -> 262040
INFO  [Service Thread] 2021-02-11 03:03:18,652 GCInspector.java:284 - ParNew GC in 204ms.  CMS Old Gen: 4534718976 -> 4535142096; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 1785200 -> 900088
INFO  [Service Thread] 2021-02-11 03:04:15,460 GCInspector.java:284 - ParNew GC in 420ms.  CMS Old Gen: 4535631288 -> 4594632944; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 119521168 -> 27375464
INFO  [Service Thread] 2021-02-11 03:05:56,051 GCInspector.java:284 - ParNew GC in 236ms.  CMS Old Gen: 4596216328 -> 4596247392; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 289592 -> 249200
INFO  [Service Thread] 2021-02-11 03:09:24,845 GCInspector.java:284 - ParNew GC in 242ms.  CMS Old Gen: 4603082800 -> 4655295752; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 133377280 -> 32703744
INFO  [Service Thread] 2021-02-11 03:09:45,778 GCInspector.java:284 - ParNew GC in 285ms.  CMS Old Gen: 4655295752 -> 4655438776; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 32703744 -> 5743152
INFO  [Service Thread] 2021-02-11 03:14:02,693 GCInspector.java:284 - ParNew GC in 295ms.  CMS Old Gen: 4658307656 -> 4700287624; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 63649976 -> 45953632
INFO  [Service Thread] 2021-02-11 03:15:25,068 GCInspector.java:284 - ParNew GC in 533ms.  CMS Old Gen: 4717789176 -> 4717833512; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 303040 -> 267560
INFO  [Service Thread] 2021-02-11 03:19:16,283 GCInspector.java:284 - ParNew GC in 383ms.  CMS Old Gen: 4719170920 -> 4777105904; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 134234296 -> 37126944
INFO  [Service Thread] 2021-02-11 03:20:35,452 GCInspector.java:284 - ParNew GC in 274ms.  CMS Old Gen: 4777690512 -> 4777720928; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 300632 -> 204840
INFO  [Service Thread] 2021-02-11 03:24:27,493 GCInspector.java:284 - ParNew GC in 255ms.  CMS Old Gen: 4784090536 -> 4838095688; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 67257840 -> 33225784
INFO  [Service Thread] 2021-02-11 03:25:00,656 GCInspector.java:284 - ParNew GC in 358ms.  CMS Old Gen: 4838230688 -> 4839354144; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 9739272 -> 623920
INFO  [Service Thread] 2021-02-11 03:29:05,009 GCInspector.java:284 - ParNew GC in 303ms.  CMS Old Gen: 4840831336 -> 4882703912; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 83610064 -> 40018184
INFO  [Service Thread] 2021-02-11 03:29:53,277 GCInspector.java:284 - ParNew GC in 313ms.  CMS Old Gen: 4898884224 -> 4899039496; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 11793616 -> 1483184
INFO  [Service Thread] 2021-02-11 03:31:21,985 GCInspector.java:284 - ParNew GC in 343ms.  CMS Old Gen: 4899629048 -> 4899666544; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 305536 -> 250176
INFO  [Service Thread] 2021-02-11 03:34:12,810 GCInspector.java:284 - ParNew GC in 419ms.  CMS Old Gen: 4900683464 -> 4959643144; Par Eden Space: 1718091776 -> 0; Par Survivor Space: 80821920 -> 22094752
```

**Comment by christidis** [comment]
I have managed to exclude all keyspaces but system keyspaces. In order to do that I used multiple `--exclude-keyspaces=` options for every keyspace and the issue went away but I don't have keyspace/table metrics.

I then included ~ 50 keyspaces (around 50%) and the timeouts came back.
```
# Wrote 28470 metrics for 130 metric families in 1.128 min
real	1m 7.72s
```

The other nodes do not have an issue with all 112 keyspaces included
```
# Wrote 43556 metrics for 130 metric families in 656.6 ms
real	0m 0.37s
```

**Comment by zegelin** [comment]
Can you add the `--enable-collector-timing` option. This will export an additional metric family `cassandra_exporter_collection_time_seconds_total` that will contain the runtime of each individual collector. This will help us narrow down which metric family is being slow.

You could be on the right track with the few cached metrics. `snapshots_size_bytes_total` is expensive to compute, as C* goes and recursively finds all snapshots and the SSTable files inside, then sums up their sizes. It can end up running the equivalent of `stat` over a few thousand files.

Are there lots of snapshots on the node?

**Comment by christidis** [comment]
Your input was very valuable, thanks! `cassandra_table_snapshots_size_bytes_total` is killing it.
![image](https://user-images.githubusercontent.com/26735628/107753445-bf44ab00-6d28-11eb-8a64-78c13fa8020c.png)

Indeed the `strace` output attached did show a lot of CPU traffic but also showed 22764 `lstat` calls.

Yes, I have many snapshots but I am copying them out of the Cassandra data directory automatically with this tool https://github.com/AppliedInfrastructure/cassandra-snapshot-tools

I am now deleting the snapshots with `nodetool clearsnapshot` and will include this in my backup process.

**Comment by christidis** [comment]
No more gaps after clearing the snapshots. Thanks @zegelin. Closing.

**Comment by zegelin** [comment]
Glad we could narrow this down. I'll make note that the behaviour needs to be improved (somehow).

That `estimated_partitions` metric looks to be more expensive than I expected too.
